config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]

      resource :check, only: [:create, :destroy]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  belongs    :string
#  gender     :integer
#  name       :string
#  subscribed :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  enum gender: { male: 0, female: 1, other: 2 }
  belongs_to :user
  has_one_attached :avatar

  validates :name, uniqueness: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.profile || current_user.build_profile
  end

  def update
    @profile = current_user.profile || current_user.build_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを編集しました'
    else
      flash.now[:alert] = '更新できませんでした'
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(
      :name,
      :belongs,
      :gender,
      :subscribed,
      :avatar
    )
  end
end

app/views/profiles/edit.html.haml
.container
  %h2.page-title Edit Profile
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'アバター'
    %div
      = f.file_field :avatar
    %div
      = f.label :name, 'name'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :belongs, 'belongs'
    %div
      = f.text_field :belongs, class: 'text'
    %div
      = f.label :gender, 'gender'
    %div
      = f.select :gender, Profile.genders.map { |k, v| [ I18n.t("enum.genders.#{k}"), k ] }, {}, { class: 'text' }
    %div
      = f.label :subscribed, '通知を受け取る'
      = f.check_box :subscribed
    = f.submit :submit, class: 'btn-submit'

app/views/profiles/show.html.haml
.container
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          = current_user.display_name
          \/ #{(I18n.t("enum.genders.#{current_user.gender}"))}
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path
      .profilePage_user_belongs
        = current_user.profile&.belongs