config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]

      resource :check, only: [:create, :destroy]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  deadline   :date
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  has_one_attached :eyecatch

  validates :title, presence: true
  validates :title, length: { minimum: 3, maximum: 50 }
  validates :title, uniqueness: true

  validates :content, presence: true
  validates :content, length: { minimum: 5, maximum: 300 }
  validates :content, uniqueness: true

  belongs_to :user
  belongs_to :board

  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy

  def check_count
    checks.count
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def show
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
    @comments = @task.comments
  end

  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params)
    if @task.save
      redirect_to board_path(board), notice: 'タスクを作成しました'
    else
      flash.now[:alert] = '作成できませんでした'
      render :new
    end
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to board_task_path(@task.board), notice: '更新しました'
    else
      render :edit
      flash.now[:alert] = '更新できませんでした'
    end
  end

  def destroy
    board = Board.find(params[:board_id])
    task = current_user.tasks.find(params[:id])
    task.destroy!
    redirect_to board_path(board), notice: 'タスクを削除しました'
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :eyecatch, :deadline).merge(user_id: current_user.id)
  end
end

app/views/tasks/edit.html.haml
.container
  %h2.page-title Edit Task
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @task, url: board_task_path(@task.board), method: 'put', local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :deadline, '期限'
    %div
      = f.date_field :deadline, class: 'text'
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'submit', class: 'btn-submit'

app/views/tasks/new.html.haml
.container
  %h2.page-title New Task
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @task, url: board_tasks_path(@task.board), method: 'post', local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :deadline, '期限'
    %div
      = f.date_field :deadline, class: 'text'
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'submit', class: 'btn-submit'

app/views/tasks/show.html.haml
.container
  - if user_signed_in? && current_user.has_written_task?(@task)
    .dropdown-mini
      = image_tag 'oval3.svg', class: 'dropdown-btn'
      .dropdown-content-mini
        %ul
          %li= link_to '編集する', edit_board_task_path(@task.board)
          %li= link_to '削除する', board_task_path(@task.board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか' }
  = link_to board_path(@board.id) do
    %h2.page-title= @task.title
  - if @task.eyecatch.attached?
    = image_tag @task.eyecatch, class: 'task_image'
  .board
    .board_content
      %p.board_detail= @task.content
      %p.deadline
        期限 : #{@task.deadline}
      - if user_signed_in?
        - if current_user.has_checked?(@task)
          = link_to board_task_check_path(board_id: @board.id, task_id: @task.id), data: { method: 'delete' } do
            %span.checked
              %i.fa.fa-check{"aria-hidden" => "true"}
                .checked_after
                  確認済み
        - else
          = link_to board_task_check_path(board_id: @board.id, task_id: @task.id), data: { method: 'post' } do
            %span.checked
              %i.fa.fa-hand-o-up{"aria-hidden" => "true"}
                .checked_before
                  未確認
      .user-info
        .boardPage_user_image
          = image_tag @task.user.avatar_image
        %p.board_user= @task.user.display_name
  %div
    %h2.comment-title Comment
  .comment_detail
    - @comments.each do |comment|
      %p.comment= comment.content
      .user-info
        .commentPage_user_image
          = image_tag comment.user.avatar_image
        %p.board_user= comment.user.display_name
  - if user_signed_in? && current_user
    = link_to new_board_task_comment_path(board_id: @board.id, task_id: @task.id) do
      %div
        .board_new
          %p + add new comment