config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]

      resource :check, only: [:create, :destroy]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  has_one_attached :eyecatch

  validates :title, presence: true
  validates :title, length: { minimum: 3, maximum: 50 }
  validates :title, uniqueness: true

  validates :content, presence: true
  validates :content, length: { minimum: 5, maximum: 200 }
  validates :content, uniqueness: true

  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: 'ボードを作成しました'
    else
      flash.now[:alert] = '作成できませんでした'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice: 'ボードを更新しました'
    else
      flash.now[:alert] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: 'ボードを削除しました'
  end

  private
  def board_params
    params.require(:board).permit(:title, :content)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/views/boards/edit.html.haml
.container
  %h2.page-title Edit Board
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, url: board_path(@board), method: 'put', local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'submit', class: 'btn-submit'

app/views/boards/index.html.haml
.container
  %h2.page-title All Boards
  - @boards.each do |board|
    .board
      .board_content
        = link_to board_path(board) do
          .board_title
            = board.title
          .board_detail
            = board.content
        .user-info
          .boardPage_user_image
            = image_tag board.user.avatar_image
          .board_user
            = board.user.display_name
  - if user_signed_in? && current_user
    = link_to new_board_path do
      .board_new
        %p + add new board

app/views/boards/new.html.haml
.container
  %h2.page-title New Board
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, url: boards_path, method: 'post', local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'submit', class: 'btn-submit'

app/views/boards/show.html.haml
.container
  - if user_signed_in? && current_user.has_written?(@board)
    .dropdown-mini
      = image_tag 'oval3.svg', class: 'dropdown-btn'
      .dropdown-content-mini
        %ul
          %li= link_to '編集する', edit_board_path(@board)
          %li= link_to '削除する', board_path(@board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか' }
  = link_to boards_path do
    %h2.page-title= @board.title
  %div
    %p.board_detail= @board.content
    .user-info
      .boardPage_user_image
        = image_tag @board.user.avatar_image
      - if @board.user.present?
        %p.board_user= @board.user.display_name
  %div
    - @tasks.each do |task|
      = link_to board_task_path(board_id: @board.id, id: task.id) do
        .board
          .board_content
            - if task.eyecatch.attached?
              = image_tag task.eyecatch, class: 'task_image'
            %p.board_title= task.title
            %p.board_detail= task.content
            %p.board_detail
              期限 : #{task.deadline}
            %p
              %i.fa.fa-user-circle{"aria-hidden" => "true"}
              チェック済み : #{task.check_count}
            .user-info
              .boardPage_user_image
                = image_tag task.user.avatar_image
              .board_user
                = task.user.display_name
  - if user_signed_in? && current_user
    %div
      = link_to new_board_task_path(@board) do
        .board_new
          %p + add new task