config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]

      resource :check, only: [:create, :destroy]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todoapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %header.header
      = link_to 'Boards', root_path, class: 'header_pageTitle'
      .dropdown
        - if user_signed_in?
          = image_tag current_user.avatar_image, class: 'header_avatar'
        - else
          = image_tag 'default-avatar.png', class: 'header_avatar'
        - if user_signed_in?
          %ul.dropdown-content
            %li= link_to 'プロフィール', profile_path
            %li= link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
        - else
          %ul.dropdown-content
            %li= link_to 'ログイン', new_user_session_path
    %hr/
    %p.notice= notice
    %p.alert= alert
    = yield